#DataSource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth2?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
# 初始化大小，最小，最大
spring:
  datasource:
    initialSize: 5
    minIdle: 5
    maxActive: 20
# 配置获取连接等待超时的时间
spring:
  datasource:
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20